# 1. NUMPY BASICS

In [ ]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np 

# Let's define a one-dimensional array 
my_list = [10, 20, 50, 60, 70]
my_list

[10, 20, 50, 60, 70]

In [ ]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
# Multi-dimensional (Matrix definition) 
matrix = np.array([[5, 8], [9, 13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [ ]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(15)
x

array([0.98475074, 0.53306556, 0.61463326, 0.28477007, 0.04002875,
       0.15621395, 0.86488375, 0.63520737, 0.0468211 , 0.54911912,
       0.28300163, 0.80924416, 0.89277928, 0.32152287, 0.87232476])

In [ ]:
# you can create a matrix of random number as well
x = np.random.rand(5, 5)
x

array([[0.49074574, 0.58475799, 0.15213804, 0.38666711, 0.45441034],
       [0.02632571, 0.11825348, 0.80672613, 0.54514786, 0.9096982 ],
       [0.81895266, 0.58159222, 0.0219584 , 0.23833528, 0.09511582],
       [0.33876621, 0.13590125, 0.89913415, 0.48323514, 0.27027316],
       [0.24539314, 0.94063078, 0.88959053, 0.46376135, 0.77901524]])

In [ ]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x

array([ 0.79693549, -0.33228416,  1.83975209,  1.22210988,  1.05852941,
       -0.03816669,  0.26132647, -1.48425968,  0.95475384,  2.0846148 ])

In [7]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 10)
x

4

In [ ]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([14, 27, 52, 73, 60, 17, 60,  1, 14, 17, 93,  5, 95, 67, 70])

In [ ]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
# Create an evenly spaced values with a step of 5
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [10]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Array of ones
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
# Matrices of ones
x = np.ones((5 , 5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Array of zeros
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [ ]:
# Let's define a one-dimensional array 
my_list = [-30, 4, 50, 60, 29, 15, 22, 90]
my_list
x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [ ]:
# Get Length of a numpy array
len(x)

8

In [ ]:
# Get shape
x.shape

(8,)

In [ ]:
# Obtain the datatype
matrix.dtype

dtype('int64')

In [ ]:
# Reshape 1D array into a matrix
z = x.reshape(2,4)
print(x)
print(z)

[-30   4  50  60  29  15  22  90]
[[-30   4  50  60]
 [ 29  15  22  90]]


In [ ]:
# Obtain the maximum element (value)
x.max()

90

In [ ]:
# Obtain the minimum element (value)
x.min()

-30

In [ ]:
# Obtain the location of the max element
x.argmax()

7

In [ ]:
# Obtain the location of the min element
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

[[8 3 3 9 6]
 [3 8 1 4 1]
 [3 6 2 1 5]
 [3 6 6 7 2]
 [6 9 1 8 6]]
1 9


# 4. MATHEMATICAL OPERATIONS

In [ ]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Add 2 numpy arrays together
sum = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
squared = x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

array([ 5.        , 20.88061302, 30.8058436 ])

# 5. SLICING AND INDEXING 

In [20]:
x = np.array([20, 40, 50, 21, 15])
x

array([20, 40, 50, 21, 15])

In [21]:
# Access specific index from the numpy array
x[0]

20

In [22]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[0:3]

array([20, 40, 50])

In [23]:
# Broadcasting, altering several values in a numpy array at once
x[0:2] = 10
x

array([10, 10, 50, 21, 15])

In [26]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[8, 3, 1, 6, 8],
       [1, 7, 7, 8, 1],
       [1, 4, 8, 1, 5],
       [1, 4, 7, 3, 3],
       [1, 8, 7, 9, 1]])

In [27]:
# Get a row from a mtrix
matrix[2]

array([1, 4, 8, 1, 5])

In [28]:
# Get one element
matrix[0][2]

1

In [29]:
mini_matrix = matrix[:3]
mini_matrix

array([[8, 3, 1, 6, 8],
       [1, 7, 7, 8, 1],
       [1, 4, 8, 1, 5]])

In [30]:
mini_matrix = matrix[2:]
mini_matrix

array([[1, 4, 8, 1, 5],
       [1, 4, 7, 3, 3],
       [1, 8, 7, 9, 1]])

In [31]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[8, 3],
       [1, 7],
       [1, 4],
       [1, 4],
       [1, 8]])

In [33]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[1, 6, 8],
       [7, 8, 1],
       [8, 1, 5],
       [7, 3, 3],
       [7, 9, 1]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

In [ ]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[7, 5, 5, 6, 4],
       [6, 9, 6, 1, 3],
       [6, 6, 9, 7, 9],
       [2, 6, 3, 1, 9],
       [1, 9, 1, 4, 6]])

In [ ]:
new_matrix = matrix[matrix>3]
new_matrix

array([7, 5, 5, 6, 4, 6, 9, 6, 6, 6, 9, 7, 9, 6, 9, 9, 4, 6])

In [ ]:
new_matrix = matrix[matrix%2==0]
new_matrix

array([6, 4, 6, 6, 6, 6, 2, 6, 4, 6])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [5]:
import numpy as np
x = np.array([[4, 6, 8, 7] , [20, 5, 6, 9]])
x

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [13]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(0, x, 20)
x

Please enter a positive integer value: 20


array([19, 14, 14, 10,  7,  4,  8, 11,  3, 11,  7, 17, 16, 12,  3, 14,  9,
       15,  6, 14])

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [14]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [16]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[-696  963  484 -788  940  206  144  -34 -251 -943  548 -693  441 -651
  -278 -564  805  734 -486 -419]
 [-788 -242  725  133  452  631  659  291 -118  233  280 -157   41    9
  -572 -950  127 -940 -554 -149]
 [ 125  904  -96  662 -840 -731  598  153  317  858 -504  829 -737  269
   908 -995  -53  482   89   34]
 [  35  469 -157 -981 -462 -669 -222   97  332  840  768  824 -935 -342
   153  987  914  129  409  350]
 [ 339  456 -475  184  984   89 -698 -926  779  967  868  329   55 -637
   290  805 -966 -399    2 -845]
 [  42 -861  556  147  -32 -645  927  220 -428  565  549  134  433  -11
  -403 -465 -559  874  755 -246]
 [ 625  768  759  352  214  985  366 -307 -514  496  611   82 -778 -220
  -174  646  363 -537  451  925]
 [ 476 -354  722  968 -358 -891 -957    9  566 -892  779    0 -853   96
   116  914 -801 -265  614  923]
 [ 828   91  111   72  987 -635    2 -342 -700  -90 -537  841  246  162
   174  630   22  734 -180 -786]
 [ 726 -194 -358  351  221 -199  591  656 -992  845 -24

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [35]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [37]:
X[4] = -1
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

In [38]:
X[:2, 3:]  = X[:2, 3:] * 2

In [39]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])